export const companyDeck = [
    {
        id: 1,
        companyName: 'Dwellings, Inc. ',
        type: 'consumer',
        initialValue: 2,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 2,
        companyName: 'Steaks, Inc. ',
        type: 'consumer',
        initialValue: 1,
        initialCarbon: 1,
        companyBank: 0,

    },
    {
        id: 3,
        companyName: 'Smartphone, Inc. ',
        type: 'consumer',
        initialValue: 3,
        initialCarbon: 1,
        companyBank: 0,
    },
    {
        id: 4,
        companyName: 'Airline, Inc. ',
        type: 'consumer',
        initialValue: 4,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 5,
        companyName: 'Aircraft, Inc. ',
        type: 'production',
        initialValue: 4,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 6,
        companyName: 'Packaging, Inc. ',
        type: 'production',
        initialValue: 2,
        initialCarbon: 1,
        companyBank: 0,
    },
    {
        id: 7,
        companyName: 'Chemicals, Inc. ',
        type: 'production',
        initialValue: 4,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 8,
        companyName: 'Software, Inc. ',
        type: 'production',
        initialValue: 4,
        initialCarbon: 1,
        companyBank: 0,
    },
    {
        id: 9,
        companyName: 'Cement, Inc. ',
        type: 'production',
        initialValue: 3,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 10,
        companyName: 'Shipping, Inc. ',
        type: 'distribution',
        initialValue: 4,
        initialCarbon: 3,
        companyBank: 0,
    },
    {
        id: 11,
        companyName: 'Road Transport, Inc. ',
        type: 'distribution',
        initialValue: 5,
        initialCarbon: 3,
        companyBank: 0,
    },
    {
        id: 12,
        companyName: 'Data & Wireless, Inc. ',
        type: 'distribution',
        initialValue: 3,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 13,
        companyName: 'Grid & Pipeline, Inc. ',
        type: 'distribution',
        initialValue: 3,
        initialCarbon: 1,
        companyBank: 0,
    },
    {
        id: 14,
        companyName: 'Oil & Gas, Inc. ',
        type: 'resource',
        initialValue: 6,
        initialCarbon: 3,
        companyBank: 0,
    },
    {
        id: 15,
        companyName: 'Sand & Metal, Inc. ',
        type: 'resource',
        initialValue: 2,
        initialCarbon: 1,
        companyBank: 0,
    },
    {
        id: 16,
        companyName: 'Farm, Inc. ',
        type: 'resource',
        initialValue: 3,
        initialCarbon: 2,
        companyBank: 0,
    },
    {
        id: 17,
        companyName: 'Wind Power, Inc. ',
        type: 'resource',
        initialValue: 3,
        initialCarbon: 0,
        companyBank: 0,
    },
    {
        id: 18,
        companyName: 'Recycling, Inc. ',
        type: 'resource',
        initialValue: 5,
        initialCarbon: 1,
        companyBank: 0,
    },

];

export const getRandomCard = (deck) =>
    deck[Math.floor(Math.random() * deck.length)];
