import {CELL_NAMES} from "../components/TestCellState/companyCellNames";

export const companyDeck = [
    {
        id: 1,
        order: 1,
        idValue: 1,
        direction: 2,
        synmain: "../img/company/14/background-1.png",
        name: 'Dwellings, Inc.',
        type: 'consumer',
        initialValue: 2,
        initialCarbon: 2,
        actualValue: 2,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC1.svg",
        cell:CELL_NAMES.c2,
    },

    {
        id: 2,
        order: 2,
        idValue: 2,
        direction: 2,
        synmain: "../img/company/14/background-1.png",
        name: 'Steaks, Inc.',
        type: 'consumer',
        initialValue: 1,
        initialCarbon: 1,
        actualValue: 1,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC2.svg",
        cell:CELL_NAMES.b1,
    },

    {
        id: 3,
        order: 3,
        idValue: 3,
        direction: 2,
        synmain: "../img/company/14/background-1.png",
        name: 'Smartphone, Inc.',
        type: 'consumer',
        initialValue: 3,
        initialCarbon: 1,
        actualValue: 3,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC3.svg",
        cell:CELL_NAMES.d2,
    },

    {
        id: 4,
        order: 4,
        idValue: 4,
        direction: 2,
        synmain: "../img/company/14/background-1.png",
        name: 'Airline, Inc.',
        type: 'consumer',
        initialValue: 4,
        initialCarbon: 2,
        actualValue: 4,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC4.svg",
        cell:CELL_NAMES.b3,
    },

    {
        id: 5,
        order: 5,
        idValue: 5,
        direction: 1,
        synmain: "../img/company/14/background-1.png",
        name: 'Aircraft, Inc.',
        type: 'production',
        initialValue: 4,
        initialCarbon: 2,
        actualValue: 4,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC5.svg",
        cell:CELL_NAMES.b2,
    },

    {
        id: 6,
        order: 6,
        idValue: 6,
        direction: 1,
        synmain: "../img/company/14/background-1.png",
        name: 'Packaging, Inc.',
        type: 'production',
        initialValue: 2,
        initialCarbon: 1,
        actualValue: 2,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC6.svg",
        cell:CELL_NAMES.b0,
    },

    {
        id: 7,
        order: 7,
        idValue: 7,
        direction: 1,
        synmain: "../img/company/14/background-1.png",
        name: 'Chemicals, Inc.',
        type: 'production',
        initialValue: 4,
        initialCarbon: 2,
        actualValue: 4,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC7.svg",
        cell:'',
    },

    {
        id: 8,
        order: 8,
        idValue: 8,
        direction: 1,
        synmain: "../img/company/14/background-1.png",
        name: 'Software, Inc.',
        type: 'production',
        initialValue: 4,
        initialCarbon: 1,
        actualValue: 4,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC8.svg",
        cell:CELL_NAMES.d1,
    },
    {
        id: 9,
        order: 9,
        idValue: 9,
        direction: 1,
        synmain: "../img/company/14/background-1.png",
        name: 'Cement, Inc.',
        type: 'production',
        initialValue: 3,
        initialCarbon: 2,
        actualValue: 3,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC9.svg",
        cell:CELL_NAMES.c1,
    },

    {
        id: 10,
        order: 10,
        idValue: 10,
        direction: 4,
        synmain: "../img/company/14/background-1.png",
        name: 'Shipping, Inc.',
        type: 'distribution',
        initialValue: 4,
        initialCarbon: 3,
        actualValue: 4,
        actualCarbon: 3,
        companyBank: 0,
        svgmain: "/img/company/CC10.svg",
        cell:'',
    },

    {
        id: 11,
        order: 11,
        idValue: 11,
        direction: 4,
        synmain: "../img/company/14/background-1.png",
        name: 'Road Transport, Inc.',
        type: 'distribution',
        initialValue: 5,
        initialCarbon: 3,
        actualValue: 5,
        actualCarbon: 3,
        companyBank: 0,
        svgmain: "/img/company/CC11.svg",
        cell:CELL_NAMES.c6,
    },

    {
        id: 12,
        order: 12,
        idValue: 12,
        direction: 4,
        synmain: "../img/company/14/background-1.png",
        name: 'Data & Wireless, Inc.',
        type: 'distribution',
        initialValue: 3,
        initialCarbon: 2,
        actualValue: 3,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC12.svg",
        cell:'',
    },

    {
        id: 13,
        order: 13,
        idValue: 13,
        direction: 4,
        synmain: "../img/company/14/background-1.png",
        name: 'Grid & Pipeline, Inc.',
        type: 'distribution',
        initialValue: 3,
        initialCarbon: 1,
        actualValue: 3,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC13.svg",
        cell:CELL_NAMES.d6,
    },

    {
        id: 14,
        order: 14,
        idValue: 14,
        direction: 3,
        synmain: "../img/company/14/background-1.png",
        name: 'Oil & Gas, Inc.',
        type: 'resource',
        initialValue: 6,
        initialCarbon: 3,
        actualValue: 6,
        actualCarbon: 3,
        companyBank: 0,
        svgmain: "/img/company/CC14.svg",
        cell:CELL_NAMES.c7,
    },

    {
        id: 15,
        order: 15,
        idValue: 15,
        direction: 3,
        synmain: "../img/company/14/background-1.png",
        name: 'Sand & Metal, Inc.',
        type: 'resource',
        initialValue: 2,
        initialCarbon: 1,
        actualValue: 2,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC15.svg",
        cell:'',
    },

    {
        id: 16,
        order: 16,
        idValue: 16,
        direction: 3,
        synmain: "../img/company/16/background-16.png",
        name: 'Farm, Inc.',
        type: 'resource',
        initialValue: 3,
        initialCarbon: 2,
        actualValue: 3,
        actualCarbon: 2,
        companyBank: 0,
        svgmain: "/img/company/CC16.svg",
        cell:'',
    },

    {
        id: 17,
        order: 17,
        idValue: 17,
        direction: 3,
        synmain: "../img/company/14/background-1.png",
        // svgmain:"../img/company/CompositeLayer.svg",
        name: 'Wind Power, Inc.',
        type: 'resource',
        initialValue: 3,
        initialCarbon: 0,
        actualValue: 3,
        actualCarbon: 0,
        companyBank: 0,
        svgmain: "/img/company/CC17.svg",
        cell:CELL_NAMES.d7,
    },

    {
        id: 18,
        order: 18,
        idValue: 18,
        direction: 3,
        synmain: "../img/company/14/background-1.png",
        name: 'Recycling, Inc.',
        type: 'resource',
        initialValue: 5,
        initialCarbon: 1,
        actualValue: 5,
        actualCarbon: 1,
        companyBank: 0,
        svgmain: "/img/company/CC18.svg",
        cell:'',
    },

];

export const getRandomCard = (deck) =>
    deck[Math.floor(Math.random() * deck.length)];
