//TODO playerView to hide team cards in multiplayer

export const teamDeck  = [
    {
        id:19,
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
    },
    {
        id:20,
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
    },
    {
        id:21,
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
    },
    {
        id:22,
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
    },
    {
        id:23,
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
    },
    {
        id:24,
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
    },
    {
        id:25,
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
    },
    {
        id:26,
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
    },
    {
        id:27,
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
    },
    {
        id:28,
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
    },
    {
        id:29,
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
        hui:"bolshoy",

    },
    {
        id:30,
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
        hui:"bolshoy",
    },
    ]
