//TODO playerView to hide team cards in multiplayer
import {CELL_NAMES} from "../components/TeamHandLayout/TeamCellNames.js";
export const teamDeck  = [
    {
        id:19,
        name:"1",
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
        svgmain: "/img/teamcards/TC3.svg",
        cell: CELL_NAMES.g0,
    },
    {
        id:20,
        name:"2",
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
        svgmain: "/img/teamcards/TC1.svg",
        cell:CELL_NAMES.h0,
    },
    {
        id:21,
        name:"3",
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
        svgmain: "/img/teamcards/TC2.svg",
        cell: CELL_NAMES.i0,
    },
    {
        id:22,
        name:"4",
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
        svgmain: "/img/teamcards/TC3.svg",
        cell:CELL_NAMES.j0,
    },
    {
        id:23,
        name:"5",
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
        svgmain: "/img/teamcards/TC1.svg",
        cell:CELL_NAMES.j1,
    },
    {
        id:24,
        name:"6",
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
        svgmain: "/img/teamcards/TC2.svg",
        cell:CELL_NAMES.j2,
    },
    {
        id:25,
        name:"7",
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
        svgmain: "/img/teamcards/TC3.svg",
        cell:CELL_NAMES.j3,
    },
    {
        id:26,
        name:"8",
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
        svgmain: "/img/teamcards/TC1.svg",
        cell:CELL_NAMES.f1,
    },
    {
        id:27,
        name:"9",
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
        svgmain: "/img/teamcards/TC2.svg",
        cell:CELL_NAMES.j4,
    },
    {
        id:28,
        name:"10",
        type: "GEO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: true,
        counter: ["GEO","GSO","GRO"],
        svgmain: "/img/teamcards/TC3.svg",
        cell:CELL_NAMES.j5,
    },
    {
        id:29,
        name:"11",
        type: "GSO",
        minSignBid: 1,
        reduceCarb: true,
        changeEvent: false,
        counter: ["GSO"],
        svgmain: "/img/teamcards/TC1.svg",
        cell:CELL_NAMES.f4,

    },
    {
        id:30,
        name:"12",
        type: "GRO",
        minSignBid: 1,
        reduceCarb: false,
        changeEvent: true,
        counter: ["GRO"],
        svgmain: "/img/teamcards/TC12.svg",
        cell:CELL_NAMES.f3,
    },
    ]
